# General Panel Configuration
# Diverse thinkers for broad, interdisciplinary discussions

panel_name: "General Panel"
description: "Diverse perspectives exploring topics across multiple domains"

participants:
  - name: "Sophia"
    gender: "female"
    personality: "collaborative"
    expertise: "ethics and moral philosophy"
    
  - name: "Marcus"
    gender: "male"
    personality: "skeptical"
    expertise: "logic and critical thinking"
    
  - name: "Aisha"
    gender: "female"
    personality: "analytical"
    expertise: "data science and statistics"
    
  - name: "James"
    gender: "male"
    personality: "creative"
    expertise: "art and aesthetics"
    
  - name: "Elena"
    gender: "female"
    personality: "assertive"
    expertise: "psychology and human behavior"

recommended_topics:
  - "What is the meaning of life?"
  - "What defines human nature?"
  - "How should we live?"
  - "What is beauty?"
  - "What is truth?"
  - "How do we know what we know?"
  - "What is the purpose of art?"
  - "What makes a good society?"